name: untitled1
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cloud_firestore: ^4.1.0
  firebase_auth: ^4.1.4
  get: ^4.6.5
  image_picker: ^0.8.6
  firebase_storage: ^11.0.6
  path: ^1.8.2
  equatable: ^2.0.3
  firebase_core: ^2.3.0
  intl: ^0.17.0
  get_storage: ^2.0.3
  translator:

dev_dependencies:
  change_app_package_name: ^1.1.0

  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  #assets:
  # - assets/
  #fonts:
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages